export const ZOOMAPI_PROVIDER_NAME = 'ZOOM_INTEGRATION_URL';
export const ZOOM_API_KEY = 'ZOOM_API_KEY';
export const ZOOM_SECRET_KEY = 'ZOOM_SECRET_KEY';
export const ZOOM_VIDEO_SCHEDULER = 'ZOOM_VIDEO_SCHEDULER';
